name: Agent Schedule Posts 🤖

on:
  #  Triggers the workflow should run every hour
  schedule:
    - cron: "0 * * * *"

jobs:
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set env vars
        run: |
          echo VENICE_TOKEN=${{ secrets.VENICE_TOKEN }} >> .env
          echo NEXT_PUBLIC_SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }} >> .env
          echo NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} >> .env
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> .env
      # Install dependencies
      - name: Install dependencies
        run: yarn install
      # Run agent post script
      - name: Run script
        run: yarn schedule-posts
