name: Agent Post 🤖

on:
  #  Triggers the workflow every day at 12:00PM PST
  schedule:
    - cron: "0 21 * * *"

jobs:
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set env vars
        run: |
          echo VENICE_TOKEN=${{ secrets.VENICE_TOKEN }} >> .env
          echo SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }} >> .env
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> .env
      # Install dependencies
      - name: Install dependencies
        run: yarn install
      # Run agent post script
      - name: Run script
        run: yarn agent-post
